"""Generate src/fig7_erd.dot (Figure 7, ERD). Columns follow the migrations on the branch.

Run from docs/manuscript/figures:  python3 src/gen_fig7.py && dot -Tpng -Gdpi=170 src/fig7_erd.dot -o fig7_erd.png
Supporting tables (cart items, favorites, in-app notifications, reports, listing photos,
order status histories, article_crop_type pivot, and framework/permission tables) are omitted.
"""

ENTITIES = {
    'farm': ('Farm', '#E1E6ED', ['PK id', 'name', 'pickup_point', 'contact_number', 'is_active']),
    'user': ('User', '#E1E6ED', ['PK id', 'FK farm_id', 'name, email, phone', 'status (role via Spatie)']),
    'crop': ('Crop Type', '#E1E6ED', ['PK id', 'label_en, label_fil', 'unit_of_measure', 'floor_price', 'max_discount']),
    'ovr': ('Farm Price Override', '#E8E6E0', ['PK id', 'FK farm_id', 'FK crop_type_id', 'floor_price, max_discount']),
    'photo': ('Farm Photo', '#E8E6E0', ['PK id', 'FK farm_id', 'path, caption']),
    'ann': ('Farm Announcement', '#E8E6E0', ['PK id', 'FK farm_id', 'FK author_id', 'audience, starts_at,', 'ends_at, notified_at']),
    'faq': ('FAQ Entry', '#E8E6E0', ['PK id', 'FK farm_id (null = system)', 'intent_key, roles', 'answer, answer_fil', 'moderated_at']),
    'art': ('Crop-Care Article', '#E8E6E0', ['PK id', 'FK farm_id', 'title, status']),
    'lst': ('Listing', '#E8E6E0', ['PK id', 'FK farmer_seller_id', 'FK farm_id', 'FK crop_type_id', 'price_per_unit', 'quantity_available,', 'quantity_held']),
    'tawad': ('Tawad Rule', '#E8E6E0', ['PK id', 'FK listing_id', 'type, discount_amount,', 'min_quantity']),
    'ord': ('Order', '#E8E6E0', ['PK id', 'FK buyer_id (null = walk-in)', 'FK farmer_seller_id', 'FK farm_id', 'source, status', 'total, amount_received', 'reminder_sent_at']),
    'item': ('Order Item', '#E8E6E0', ['PK id', 'FK order_id', 'FK listing_id', 'quantity, unit_price,', 'tawad_amount']),
    'msg': ('Order Message', '#E8E6E0', ['PK id', 'FK order_id', 'FK user_id', 'body']),
    'rev': ('Review', '#E8E6E0', ['PK id', 'FK order_id', 'FK buyer_id', 'FK farmer_seller_id', 'rating, comment']),
    'exp': ('Export Log', '#E8E6E0', ['PK id', 'FK user_id', 'type, filters, row_count']),
    'del': ('Account Deletion Request', '#E8E6E0', ['PK id', 'FK user_id', 'FK processed_by', 'status']),
}

# (from, to, from cardinality, to cardinality, label)
RELATIONSHIPS = [
    ('farm', 'user', '1', 'N', 'members'),
    ('farm', 'ovr', '1', 'N', ''),
    ('crop', 'ovr', '1', 'N', ''),
    ('farm', 'photo', '1', 'N', ''),
    ('farm', 'ann', '1', 'N', ''),
    ('farm', 'faq', '1', '0..N', ''),
    ('farm', 'art', '1', 'N', 'writes'),
    ('crop', 'art', 'M', 'N', 'tagged to'),
    ('user', 'lst', '1', 'N', 'sells'),
    ('crop', 'lst', '1', 'N', ''),
    ('lst', 'tawad', '1', 'N', ''),
    ('user', 'ord', '1', 'N', 'places / fulfils'),
    ('ord', 'item', '1', 'N', ''),
    ('lst', 'item', '1', 'N', ''),
    ('ord', 'msg', '1', 'N', ''),
    ('ord', 'rev', '1', '0..1', ''),
    ('user', 'exp', '1', 'N', ''),
    ('user', 'del', '1', 'N', ''),
]


def main() -> None:
    out = [
        '// Figure 7. Entity relationship diagram of AniHow (v3.5). Generated by gen_fig7.py; edit that file, not this one.',
        'digraph G {',
        '  graph [rankdir=LR, nodesep=0.35, ranksep=1.0, pad=0.3, fontname="Liberation Sans", splines=true];',
        '  node  [shape=plain, fontname="Liberation Sans", fontsize=11];',
        '  edge  [arrowhead=none, penwidth=1.1, color="#333333", fontname="Liberation Sans", fontsize=10, labelfontsize=10];',
    ]
    for key, (title, fill, rows) in ENTITIES.items():
        cells = ''.join(f'<TR><TD ALIGN="LEFT" BALIGN="LEFT">{row}</TD></TR>' for row in rows)
        out.append(
            f'  {key} [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="4">'
            f'<TR><TD BGCOLOR="{fill}"><B>{title}</B></TD></TR>{cells}</TABLE>>];'
        )
    for src, dst, src_card, dst_card, label in RELATIONSHIPS:
        extra = f', label="{label}"' if label else ''
        out.append(f'  {src} -> {dst} [taillabel="{src_card}", headlabel="{dst_card}"{extra}];')
    out += ['  {rank=same; farm; crop}', '  {rank=same; user; ovr; art}', '}']
    with open('src/fig7_erd.dot', 'w') as handle:
        handle.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
