[program:anihow-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/anihow/artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=/var/www/anihow
user=anihow
numprocs=2
autostart=true
autorestart=true
stopwaitsecs=3600
redirect_stderr=true
stdout_logfile=/var/www/anihow/storage/logs/queue.log

[program:anihow-reverb]
command=php /var/www/anihow/artisan reverb:start --host=127.0.0.1 --port=8080
directory=/var/www/anihow
user=anihow
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/anihow/storage/logs/reverb.log
